# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'LoginWindow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginWindow
  pod 'AWSUserPoolsSignIn', '~>2.6.13'
  pod 'AWSAuthUI', '~>2.6.13'
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSDynamoDB', '~> 2.6.13'

  target 'LoginWindowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginWindowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
