//
//  Trip.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Trip: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _type: String?
    var _month: String?
    var _date: String?
    var _day: NSNumber?
    var _length: NSNumber?
    var _creationDate: String?
    var _numCommitted: NSNumber?
    var _numParticipants: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "travelbuddyapp-mobilehub-1128196265-Trip"
    }
    
    class func hashKeyAttribute() -> String {

        return "_type"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_month"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_type" : "Type",
               "_month" : "Month",
               "_date" : "Date",
               "_day" : "Day",
               "_length" : "Length",
               "_creationDate" : "creationDate",
               "_numCommitted" : "numCommitted",
               "_numParticipants" : "numParticipants",
        ]
    }
}
