//
//  Trip.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB


class Trip: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _name: String?               //user entered
    @objc var _type: String?               //user entered
    @objc var _destination: String?        //user entered
    @objc var _date: String?
    @objc var _startDate:  String?         //user entered
    @objc var _endDate: String?            //user entered
    @objc var _length: NSNumber?
    @objc var _numParticipants: NSNumber?  //user entered
    @objc var _numCommitted: NSNumber?
    @objc var _expectedCost: NSNumber?     //user entered
    @objc var _notes: String?              //user entered
    
    
    class func dynamoDBTableName() -> String {
        
        //return "travelbuddyapp-mobilehub-1128196265-Trip"
        return "Trips"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_type"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_date"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_name" : "Name",
            "_type" : "Type",
            "_destination": "Destination",
            "_date" : "Date",
            "_startDate": "StartDate",
            "_endDate": "EndDate",
            "_length" : "Length",
            "_numParticipants" : "NumParticipants",
            "_numCommitted" : "NumCommitted",
            "_expectedCost": "ExpectedCost",
            "_notes": "Notes"
        ]
    }
}
